[dev]
    command="yarn dev"
    port=8888
    targetPort=3000
    framework='#custom'
    publish="./web/__sapper/__/build"
    autoLaunch = true
[build]
    functions = "/.netlify/functions/"
[[redirects]]
    from = "/netlify/*"
    to="/.netlify/functions/:splat"
    status=200
[context.test.environment]
  SANITY_STUDIO_API_DATASET = 'development'
  SANITY_STUDIO_ACTIVE_ENV = 'development'
  SANITY_STUDIO_PROJECT_NAME = 'stille disco (DEV)'
[context.main.environment]
  SANITY_STUDIO_API_DATASET = 'production'
  SANITY_STUDIO_ACTIVE_ENV = 'production'
  SANITY_STUDIO_PROJECT_NAME = 'stille disco'